name: sqlite3_driver
version: 0.0.4
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: SQLite database engine driver.
homepage: https://github.com/mezoni/sqlite3_driver
dependencies:
  binary_interop: any
  libc: any
  sqlite3_bindings: '^0.0.8'
dev_dependencies:
  build_tools: any
  file_utils: any
  test: any